### ISSUE TITLE
Runtime Error when saving model

### ISSUE THREAD

**Issue by lesnikow** [ajbrock/BigGAN-PyTorch#15]
Hello, I'm having the following run-time error when saving my model at the first model save point. Any ideas or help would be excellent. Thank you. 

`RuntimeError: The size of tensor a (25) must match the size of tensor b (50) at non-singleton dimension 0`

More context:
```247/250 ( 98.40%) (TE/ETA: 1:14 / 0:01) itr: 1997, G_loss : +0.263, D_loss_real : +0.755, D_loss_fake : +0.248/250 ( 98.80%) (TE/ETA: 1:15 / 0:00) itr: 1998, G_loss : -0.114, D_loss_real : +0.762, D_loss_fake : +0.249/250 ( 99.20%) (TE/ETA: 1:15 / 0:00) itr: 1999, G_loss : +0.430, D_loss_real : +0.907, D_loss_fake : +0.250/250 ( 99.60%) (TE/ETA: 1:15 / 0:00) itr: 2000, G_loss : +1.064, D_loss_real : +1.046, D_loss_fake : +0.183 Saving weights to weights/BigGAN_C100_seed1_Gch64_Dch64_bs50_nDs4_Glr2.0e-04_Dlr2.0e-04_Gnlrelu_Dnlrelu_GinitN02_DinitN02_ema...
Saving weights to weights/BigGAN_C100_seed1_Gch64_Dch64_bs50_nDs4_Glr2.0e-04_Dlr2.0e-04_Gnlrelu_Dnlrelu_GinitN02_DinitN02_ema/copy0...
Traceback (most recent call last):
  File "train.py", line 227, in <module>
    main()
  File "train.py", line 224, in main
    run(config)
  File "train.py", line 206, in run
    state_dict, config, experiment_name)
  File "/workspace/BigGAN-PyTorch/train_fns.py", line 140, in save_and_sample
    z_=z_)
  File "/workspace/BigGAN-PyTorch/utils.py", line 895, in sample_sheet
    o = nn.parallel.data_parallel(G, (z_[:classes_per_sheet], G.shared(y)))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 207, in data_parallel
    outputs = parallel_apply(replicas, inputs, module_kwargs, used_device_ids)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/BigGAN-PyTorch/BigGAN.py", line 248, in forward
    h = block(h, ys[index])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/BigGAN-PyTorch/layers.py", line 399, in forward
    h = self.activation(self.bn1(x, y))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/BigGAN-PyTorch/layers.py", line 325, in forward
    return out * gain + bias
r```

**Comment by ajbrock** [comment]
Ah, this would appear to be an issue with `classes_per_sheet` being greater than the overall batch size. Should be fixed with [this commit](https://github.com/ajbrock/BigGAN-PyTorch/commit/d2c933a1bd58acb543a8d6481cbcaccf350220f3).

**Comment by lesnikow** [comment]
I tried out that commit, though this leads to this`AttributeError: 'Tensor' object has no attribute 'sample_'`

Here's more context:
```2/250 (  0.40%) (TE/ETA: 0:10 / 42:58) itr: 2, G_loss : +6.914, D_loss_real : +1.965, D_loss_fake : +3/250 (  0.80%) (TE/ETA: 0:10 / 22:06) itr: 3, G_loss : -0.484, D_loss_real : +2.890, D_loss_fake : +4/250 (  1.20%) (TE/ETA: 0:11 / 15:10) itr: 4, G_loss : +4.860, D_loss_real : +0.245, D_loss_fake : +5/250 (  1.60%) (TE/ETA: 0:11 / 11:40) itr: 5, G_loss : +1.955, D_loss_real : +1.877, D_loss_fake : +6/250 (  2.00%) (TE/ETA: 0:11 / 9:34) itr: 6, G_loss : +2.645, D_loss_real : +0.091, D_loss_fake : +17/250 (  2.40%) (TE/ETA: 0:12 / 8:08) itr: 7, G_loss : -1.358, D_loss_real : +1.278, D_loss_fake : +08/250 (  2.80%) (TE/ETA: 0:12 / 7:08) itr: 8, G_loss : -1.030, D_loss_real : +0.072, D_loss_fake : +19/250 (  3.20%) (TE/ETA: 0:12 / 6:22) itr: 9, G_loss : -0.929, D_loss_real : +0.388, D_loss_fake : +010/250 (  3.60%) (TE/ETA: 0:12 / 5:46) Deleting singular value logs...
11/250 (  4.00%) (TE/ETA: 0:13 / 5:18) itr: 11, G_loss : +0.418, D_loss_real : +0.149, D_loss_fake : 12/250 (  4.40%) (TE/ETA: 0:13 / 4:55) itr: 12, G_loss : -0.430, D_loss_real : +0.369, D_loss_fake : 13/250 (  4.80%) (TE/ETA: 0:13 / 4:36) itr: 13, G_loss : -0.668, D_loss_real : +0.540, D_loss_fake : 14/250 (  5.20%) (TE/ETA: 0:14 / 4:20) itr: 14, G_loss : -0.389, D_loss_real : +0.516, D_loss_fake : 15/250 (  5.60%) (TE/ETA: 0:14 / 4:05) itr: 15, G_loss : -0.387, D_loss_real : +1.293, D_loss_fake : 16/250 (  6.00%) (TE/ETA: 0:14 / 3:53) itr: 16, G_loss : +0.582, D_loss_real : +1.693, D_loss_fake : 17/250 (  6.40%) (TE/ETA: 0:15 / 3:41) itr: 17, G_loss : +0.666, D_loss_real : +0.569, D_loss_fake : 18/250 (  6.80%) (TE/ETA: 0:15 / 3:32) itr: 18, G_loss : +1.341, D_loss_real : +0.089, D_loss_fake : 19/250 (  7.20%) (TE/ETA: 0:15 / 3:23) itr: 19, G_loss : +0.691, D_loss_real : +0.333, D_loss_fake : 20/250 (  7.60%) (TE/ETA: 0:16 / 3:15) itr: 20, G_loss : +0.195, D_loss_real : +0.000, D_loss_fake : +1.365 Saving weights to weights/BigGAN_C100_seed2_Gch64_Dch64_bs50_nDs4_Glr2.0e-04_Dlr2.0e-04_Gnlrelu_Dnlrelu_GinitN02_DinitN02_ema...
Saving weights to weights/BigGAN_C100_seed2_Gch64_Dch64_bs50_nDs4_Glr2.0e-04_Dlr2.0e-04_Gnlrelu_Dnlrelu_GinitN02_DinitN02_ema/copy0...
Traceback (most recent call last):
  File "train.py", line 227, in <module>
    main()
  File "train.py", line 224, in main
    run(config)
  File "train.py", line 206, in run
    state_dict, config, experiment_name)
  File "/workspace/BigGAN-PyTorch/train_fns.py", line 140, in save_and_sample
    z_=z_)
  File "/workspace/BigGAN-PyTorch/utils.py", line 892, in sample_sheet
    z_.sample_()
AttributeError: 'Tensor' object has no attribute 'sample_'
```

Any ideas? Thank you

**Comment by lesnikow** [comment]
I could comment out line 892 and not sample, but I would prefer to sample while training if possible.

**Comment by ajbrock** [comment]
There's just an issue in my logic (it's 10PM on a Friday night and I'm coding over an ssh connection on my phone <_<) this [most recent commit](https://github.com/ajbrock/BigGAN-PyTorch/commit/8c940f41708cdac2ea998786e16ba1f7e30b2774) should handle it.

**Comment by lesnikow** [comment]
Not a problem. Thanks, let me try that commit.

**Comment by ajbrock** [comment]
Actually one more mistake in my logic (I flipped the greater than the wrong way), but NOW [this one](https://github.com/ajbrock/BigGAN-PyTorch/commit/ba3d05754120e9d3b68313ec7b0f9833fc5ee8bc) should handle it.
