### ISSUE TITLE
RuntimeError: The size of tensor a (1000) must match the size of tensor b (10) at non-singleton dimension 0

### ISSUE THREAD

**Issue by wtupc96** [ajbrock/BigGAN-PyTorch#50]
Hi, I want to fine tune BigGAN on my own dataset which has 10 classes. I have modified num_classess and made sure that the checkpoint can be loaded into the model, but when I run it, it gave me this Error. I cannot figure out what else config maybe left out. Do I need to modify the number of classes of inception_v3 model? 

1/488 (  0.00%) Traceback (most recent call last):
  File "../train.py", line 228, in <module>
    main()
  File "../train.py", line 224, in main
    run(config)
  File "../train.py", line 184, in run
    metrics = train(x, y)
  File "/cache/code/BigGAN-PyTorch/train_fns.py", line 58, in train
    D.optim.step()
  File "/root/miniconda3/lib/python3.6/site-packages/torch/optim/adam.py", line 93, in step
    exp_avg.mul_(beta1).add_(1 - beta1, grad)
RuntimeError: The size of tensor a (1000) must match the size of tensor b (10) at non-singleton dimension 0

**Comment by janzd** [comment]
I explained how to train with a dataset of a different number of classes in this issue.
https://github.com/ajbrock/BigGAN-PyTorch/issues/43#issuecomment-559071781
