### ISSUE TITLE
Error encountered in parallel training

### ISSUE THREAD

**Issue by KenyonY** [ajbrock/BigGAN-PyTorch#52]
Hello, I was training with my own dataset, which has 3 categories and 10K images in each. I use the launch_BigGAN_bs256x8.sh script. 
The training exits with the following error message: 
```bash
157/157 ( 99.36%) (TE/ET1k: 72:21 / 391:26) Traceback (most recent call last):_real : +0.914, D_loss_fake : +0.899
  File "train.py", line 227, in <module>
    main()
  File "train.py", line 224, in main
    run(config)
  File "train.py", line 184, in run
    metrics = train(x, y)
  File "/share/vision/BigGAN-PyTorch/train_fns.py", line 42, in train
    split_D=config['split_D'])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 7 on device 7.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 2 required positional arguments: 'z' and 'gy'
```
Looks like something wrong with data parallel mode. Tried with pytorch 1.0.1 and 1.2.0, the error stays the same. 
Could you take a look at it, please?

**Comment by ktiwary2** [comment]
I am having the same error, what how did you fix it?

**Comment by KenyonY** [comment]
> I am having the same error, what how did you fix it?

Unfortunately, I didn't solve the problem a year ago.
